### ISSUE TITLE
FPGA examples main testbenches are not running, i.e., in folder corundum/fpga/mqnic/VCU108/fpga_10g/tb/fpga_core

### ISSUE THREAD

**Issue by zaidtahirbutt** [corundum/corundum#108]
I tried running the main FPGA examples testbenches e.g., in folder **corundum/fpga/mqnic/VCU108/fpga_10g/tb/fpga_core**, but I was getting a the same error in a few different FPGA testbenches that I tried. 

The error has been pasted below: (looks like a cocotb pcie error)

![image](https://user-images.githubusercontent.com/25262332/177407628-f8e82487-7adf-4feb-9fae-8fb24b89b4fb.png)

I wanted to run the main tb in order to see the dataflow.  I ran the tb using "make WAVES=1". Pytest wasnt even working as well.

**Comment by alexforencich** [comment]
This is a version mismatch between cocotbext-pcie and what the testbenches expect.  There have recently been a couple of backwards-incompatible changes in cocotbext-pcie, and the code in the main Corundum repo has not yet been updated.  So you'll need to use the version of cocotbext-pcie specified in tox.ini.  Hopefully I'll have the main repo updated within the next couple of weeks, after verifying that everything works correctly.  Alternatively, you can use the code on my development fork, which should work with the latest version of cocotbext-pcie (but potentially could have a bug in it that I have not yet fixed).
