### ISSUE TITLE
How to see what "parameter" and "localparamter" values are in the cocotb simulation?

### ISSUE THREAD

**Issue by zaidtahirbutt** [corundum/corundum#109]
Is there a way to display the value of a particular parameter or localparameter when the simulation of an example fpga in Corundum is done using "make WAVES=1"?  (many parameters are in the form of equations, so it would be easier if I can just display their values in the simulation).

**Comment by alexforencich** [comment]
Depends on the simulator, and the parameter.  Some simulators will include parameters in the waveform dumps, so you can just look at the values.  If this isn't the case, then there are a couple of options.  If the parameter drives a signal width, then you can simply look at the signal width in the waveform dump.  If this isn't the case, then a simple thing you can do is add an initial block with `$display` statements to print out the parameter values you're interested in.

**Comment by zaidtahirbutt** [comment]
Thanks. Using $display would be an easy and quick solution.
