### ISSUE TITLE
Understanding complex modules like Queue Manager 

### ISSUE THREAD

**Issue by zaidtahirbutt** [corundum/corundum#119]
Hi, I was looking at the queue_manager module and there were some operations like axil reads and writes happening at the start of the simulation (AU50 testbench), also there are some address mappings like: 

> // log queue size
                s_axil_rdata_next[7:0] = queue_ram_read_data_log_queue_size;

My question is, will I be able to understand all the different modules in Corundum with just looking at the code (and Corundum docs)? 

Also since I don't have experience with PCIe, and your PCIe repository doesn't have a separate dox, so it's a bit tricky to understand the PCIe part as well. Can the PCIe part be understood with just looking at the code as well?

**Comment by alexforencich** [comment]
It should be possible to figure out how everything works from looking at the code, naturally.  But possibly not all that straightforward.  Not everything is documented at the moment, the documentation is a bit of a work-in-progress, and there are modules that are going to be replaced/rewritten so it makes little sense to document the old versions of those modules.

If you have questions, feel free to hop on Zulip and ask: https://corundum.zulipchat.com/

**Comment by zaidtahirbutt** [comment]
@alexforencich got it. The code is written really well along with the simulations so I do get most of whats happening. 

I just joined  https://corundum.zulipchat.com/. I ask most of my questions here so that if people have similar questions while looking at the code, they can see your answers (I look at your answers to other people's questions here as well). Thanks for helping!
