### ISSUE TITLE
ethtool on AU50 interfaces

### ISSUE THREAD

**Issue by vaniaprkl** [corundum/corundum#149]
Hi,

I was trying to increase the rx queue length of the interface using "ethtool" but cant. Seems like the feature is not built?
I am running 4 x 10G interfaces on an AU50. I want to increase the rx queue to max to reduce the chance of drops while receiving. 

Thanks

**Comment by alexforencich** [comment]
Those changes have not yet made it into this repo, try my development repo here: https://github.com/ucsdsysnet/corundum

**Comment by vaniaprkl** [comment]
The ethtool in your development repo works!! Thank you. 
Is there a merge in the works?
