### ISSUE TITLE
problem while building the driver

### ISSUE THREAD

**Issue by chenker-alt** [corundum/corundum#194]
I've just got this problem while building the driver. So I'm using an Alveo U200 100g version, I've installed the  kernnel source code and its headers, I ran the synthesis and implementation and generated the bitstream, but when I tried to build the driver, I got this issue. The kernel I'm using is Linux fpga 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
![Screenshot from 2024-05-30 12-01-35](https://github.com/corundum/corundum/assets/123405083/66bcf95f-3dd0-41fe-bcad-d31c1a2039b0)

**Comment by JeffMY05** [comment]
I also got this problem which I believe is the kernel version mismatch. Which Linux kernel version should we upgrade our system to?

**Comment by wegul** [comment]
Mine is 6.5.0 and no errors shown.

**Comment by alexforencich** [comment]
I recently added some devlink-related ifdefs on my dev repo: https://github.com/alexforencich/corundum .  Does the driver in that repo build correctly?

**Comment by alexforencich** [comment]
(and yes, this is a version-related issue...but this sort of thing should be fixable with some ifdefs)

**Comment by chenker-alt** [comment]
The devlink issue has been fixed, but now I have an issue with mqnic.ko: 
![image](https://github.com/corundum/corundum/assets/123405083/03e9a16a-e0f7-42e0-974b-913c3978030c)

**Comment by alexforencich** [comment]
Huh.  Did you do a make clean first?

**Comment by chenker-alt** [comment]
Oh, I see the problem, it should be good now. Thanks!
