### ISSUE TITLE
fix typo in test_fpga_core.py

### ISSUE THREAD

**Issue by kaoruzhu1** [corundum/corundum#20]
In test_fpga_core.py:

orginal:
    dev.user_clock_frequency = 250e6

should be:
   dev.user_clk_frequency = 250e6

note: it will be ok if core_freq is fixed at 250MHz, when switching to other freq. (e.g. Gen2@125MHz),  simulation fails.

**Comment by alexforencich** [comment]
Ah, thanks for letting me know, should be fixed now.

**Comment by kaoruzhu1** [comment]
remove additional ';' @line 684 in tx_scheduler_rr.v
